import { Player, PlayerStats, ComparisonData, PlayerHistory } from '../types/player';

export const mockPlayers: Player[] = [
  { id: 1, name: 'LeBron James', team: 'Los Angeles Lakers', position: 'F' },
  { id: 2, name: 'Stephen Curry', team: 'Golden State Warriors', position: 'G' },
  { id: 3, name: 'Kevin Durant', team: 'Phoenix Suns', position: 'F' },
  { id: 4, name: 'Giannis Antetokounmpo', team: 'Milwaukee Bucks', position: 'F' },
  { id: 5, name: 'Joel Embiid', team: 'Philadelphia 76ers', position: 'C' },
  { id: 6, name: 'Luka Doncic', team: 'Dallas Mavericks', position: 'G' },
  { id: 7, name: 'Nikola Jokic', team: 'Denver Nuggets', position: 'C' },
  { id: 8, name: 'Jayson Tatum', team: 'Boston Celtics', position: 'F' },
  { id: 9, name: 'Devin Booker', team: 'Phoenix Suns', position: 'G' },
  { id: 10, name: 'Ja Morant', team: 'Memphis Grizzlies', position: 'G' },
];

export const mockPlayerStats: Record<number, PlayerStats> = {
  1: {
    points: 28.9,
    assists: 7.5,
    rebounds: 8.3,
    steals: 1.3,
    blocks: 0.9,
    turnovers: 3.2,
    fieldGoalPercentage: 53.5,
    threePointPercentage: 32.1,
    freeThrowPercentage: 75.9,
    gamesPlayed: 55,
    minutesPerGame: 35.5,
    plusMinus: 5.8,
    playerEfficiencyRating: 25.6,
    fieldGoalsMade: 10.2,
    fieldGoalsAttempted: 19.1,
    freeThrowsMade: 5.8,
    freeThrowsAttempted: 7.6,
    offensiveRebounds: 1.2,
    defensiveRebounds: 7.1,
    personalFouls: 1.8,
    defensiveRating: 106.5
  },
  2: {
    points: 29.4,
    assists: 6.3,
    rebounds: 6.1,
    steals: 0.9,
    blocks: 0.4,
    turnovers: 3.1,
    fieldGoalPercentage: 48.7,
    threePointPercentage: 42.7,
    freeThrowPercentage: 92.3,
    gamesPlayed: 56,
    minutesPerGame: 34.7,
    plusMinus: 6.4,
    playerEfficiencyRating: 24.8,
    fieldGoalsMade: 9.8,
    fieldGoalsAttempted: 20.1,
    freeThrowsMade: 4.9,
    freeThrowsAttempted: 5.3,
    offensiveRebounds: 0.8,
    defensiveRebounds: 5.3,
    personalFouls: 2.1,
    defensiveRating: 108.2
  },
  3: {
    points: 31.2,
    assists: 5.7,
    rebounds: 6.9,
    steals: 0.9,
    blocks: 1.2,
    turnovers: 3.1,
    fieldGoalPercentage: 51.8,
    threePointPercentage: 38.6,
    freeThrowPercentage: 89.5,
    gamesPlayed: 62,
    minutesPerGame: 36.8,
    plusMinus: 6.8,
    playerEfficiencyRating: 26.2,
    fieldGoalsMade: 10.5,
    fieldGoalsAttempted: 20.2,
    freeThrowsMade: 7.2,
    freeThrowsAttempted: 7.8,
    offensiveRebounds: 0.9,
    defensiveRebounds: 6.0,
    personalFouls: 2.3,
    defensiveRating: 107.8
  },
  4: {
    points: 31.8,
    assists: 5.8,
    rebounds: 11.2,
    steals: 1.1,
    blocks: 1.8,
    turnovers: 3.4,
    fieldGoalPercentage: 57.8,
    threePointPercentage: 28.4,
    freeThrowPercentage: 68.5,
    gamesPlayed: 58,
    minutesPerGame: 33.8,
    plusMinus: 8.2,
    playerEfficiencyRating: 28.3,
    fieldGoalsMade: 11.4,
    fieldGoalsAttempted: 19.8,
    freeThrowsMade: 6.8,
    freeThrowsAttempted: 9.9,
    offensiveRebounds: 2.4,
    defensiveRebounds: 8.8,
    personalFouls: 3.1,
    defensiveRating: 105.3
  },
  5: {
    points: 33.5,
    assists: 4.8,
    rebounds: 10.2,
    steals: 1.1,
    blocks: 1.7,
    turnovers: 3.4,
    fieldGoalPercentage: 54.8,
    threePointPercentage: 34.7,
    freeThrowPercentage: 85.5,
    gamesPlayed: 58,
    minutesPerGame: 34.6,
    plusMinus: 7.8,
    playerEfficiencyRating: 31.2,
    fieldGoalsMade: 11.2,
    fieldGoalsAttempted: 20.4,
    freeThrowsMade: 8.9,
    freeThrowsAttempted: 10.4,
    offensiveRebounds: 2.1,
    defensiveRebounds: 8.1,
    personalFouls: 2.8,
    defensiveRating: 104.2
  },
  6: {
    points: 32.5,
    assists: 9.2,
    rebounds: 8.7,
    steals: 1.4,
    blocks: 0.5,
    turnovers: 3.9,
    fieldGoalPercentage: 49.8,
    threePointPercentage: 38.2,
    freeThrowPercentage: 88.5,
    gamesPlayed: 62,
    minutesPerGame: 36.8,
    plusMinus: 6.9,
    playerEfficiencyRating: 29.8,
    fieldGoalsMade: 10.8,
    fieldGoalsAttempted: 21.7,
    freeThrowsMade: 7.6,
    freeThrowsAttempted: 8.6,
    offensiveRebounds: 0.8,
    defensiveRebounds: 7.9,
    personalFouls: 2.4,
    defensiveRating: 109.5
  },
  7: {
    points: 25.4,
    assists: 9.8,
    rebounds: 12.3,
    steals: 1.2,
    blocks: 0.8,
    turnovers: 3.5,
    fieldGoalPercentage: 63.2,
    threePointPercentage: 35.8,
    freeThrowPercentage: 81.2,
    gamesPlayed: 57,
    minutesPerGame: 33.6,
    plusMinus: 9.4,
    playerEfficiencyRating: 24.9,
    fieldGoalsMade: 9.8,
    fieldGoalsAttempted: 15.5,
    freeThrowsMade: 5.8,
    freeThrowsAttempted: 6.3,
    offensiveRebounds: 0.9,
    defensiveRebounds: 6.4,
    personalFouls: 2.1,
    defensiveRating: 107.8
  },
  8: {
    points: 30.2,
    assists: 4.9,
    rebounds: 8.8,
    steals: 1.0,
    blocks: 0.7,
    turnovers: 2.8,
    fieldGoalPercentage: 47.8,
    threePointPercentage: 36.5,
    freeThrowPercentage: 85.4,
    gamesPlayed: 59,
    minutesPerGame: 35.8,
    plusMinus: 5.9,
    playerEfficiencyRating: 23.7,
    fieldGoalsMade: 4.9,
    fieldGoalsAttempted: 10.3,
    freeThrowsMade: 4.9,
    freeThrowsAttempted: 5.3,
    offensiveRebounds: 0.8,
    defensiveRebounds: 5.3,
    personalFouls: 2.1,
    defensiveRating: 108.2
  },
  9: {
    points: 27.8,
    assists: 5.4,
    rebounds: 4.5,
    steals: 0.9,
    blocks: 0.4,
    turnovers: 2.6,
    fieldGoalPercentage: 48.5,
    threePointPercentage: 38.2,
    freeThrowPercentage: 87.8,
    gamesPlayed: 53,
    minutesPerGame: 34.2,
    plusMinus: 4.8,
    playerEfficiencyRating: 23.7,
    fieldGoalsMade: 5.4,
    fieldGoalsAttempted: 11.2,
    freeThrowsMade: 4.8,
    freeThrowsAttempted: 5.6,
    offensiveRebounds: 0.4,
    defensiveRebounds: 4.5,
    personalFouls: 1.8,
    defensiveRating: 107.8
  },
  10: {
    points: 26.2,
    assists: 8.1,
    rebounds: 5.9,
    steals: 1.5,
    blocks: 0.3,
    turnovers: 3.4,
    fieldGoalPercentage: 46.8,
    threePointPercentage: 32.4,
    freeThrowPercentage: 74.8,
    gamesPlayed: 51,
    minutesPerGame: 32.8,
    plusMinus: 4.2,
    playerEfficiencyRating: 23.7,
    fieldGoalsMade: 8.1,
    fieldGoalsAttempted: 17.3,
    freeThrowsMade: 4.2,
    freeThrowsAttempted: 5.6,
    offensiveRebounds: 0.3,
    defensiveRebounds: 5.9,
    personalFouls: 1.8,
    defensiveRating: 107.8
  },
};

export const mockHeadToHead: Record<string, ComparisonData> = {
  '1-2': {
    matchups: 28,
    player1Wins: 15,
    player2Wins: 13,
    averagePointDiff: 3.2,
    headToHeadStats: {
      player1: {
        points: 28.5,
        assists: 8.1,
        rebounds: 7.4,
        steals: 1.3,
        blocks: 0.9,
        turnovers: 3.4,
        fieldGoalPercentage: 51.2,
        threePointPercentage: 34.8,
        freeThrowPercentage: 72.5,
        gamesPlayed: 30,
        minutesPerGame: 36.2,
        plusMinus: 5.8,
        playerEfficiencyRating: 24.9,
        fieldGoalsMade: 10.2,
        fieldGoalsAttempted: 19.8,
        freeThrowsMade: 6.5,
        freeThrowsAttempted: 9.0,
        offensiveRebounds: 1.2,
        defensiveRebounds: 6.2,
        personalFouls: 2.1,
        defensiveRating: 106.8
      },
      player2: {
        points: 27.8,
        assists: 6.5,
        rebounds: 5.2,
        steals: 1.4,
        blocks: 0.3,
        turnovers: 2.9,
        fieldGoalPercentage: 47.8,
        threePointPercentage: 41.5,
        freeThrowPercentage: 90.8,
        gamesPlayed: 30,
        minutesPerGame: 35.1,
        plusMinus: 6.2,
        playerEfficiencyRating: 23.7,
        fieldGoalsMade: 9.8,
        fieldGoalsAttempted: 18.5,
        freeThrowsMade: 5.8,
        freeThrowsAttempted: 7.2,
        offensiveRebounds: 0.8,
        defensiveRebounds: 4.4,
        personalFouls: 2.4,
        defensiveRating: 108.2
      }
    },
    lastMatchup: {
      date: '2024-01-15',
      winner: 1,
      player1Points: 32,
      player2Points: 29,
      gameId: 12345
    }
  },
  '1-3': {
    matchups: 25,
    player1Wins: 12,
    player2Wins: 13,
    averagePointDiff: 4.5,
    headToHeadStats: {
      player1: {
        points: 26.8,
        assists: 7.9,
        rebounds: 7.2,
        steals: 1.2,
        blocks: 0.8,
        turnovers: 3.1,
        fieldGoalPercentage: 52.4,
        threePointPercentage: 35.8,
        freeThrowPercentage: 82.5,
        gamesPlayed: 25,
        minutesPerGame: 34.8,
        plusMinus: 6.4,
        playerEfficiencyRating: 24.9,
        fieldGoalsMade: 9.8,
        fieldGoalsAttempted: 18.7,
        freeThrowsMade: 5.8,
        freeThrowsAttempted: 7.0,
        offensiveRebounds: 1.1,
        defensiveRebounds: 6.1,
        personalFouls: 2.3,
        defensiveRating: 107.2
      },
      player2: {
        points: 28.4,
        assists: 5.5,
        rebounds: 6.8,
        steals: 1.4,
        blocks: 0.3,
        turnovers: 2.9,
        fieldGoalPercentage: 47.8,
        threePointPercentage: 41.5,
        freeThrowPercentage: 90.8,
        gamesPlayed: 25,
        minutesPerGame: 35.1,
        plusMinus: 6.2,
        playerEfficiencyRating: 23.7,
        fieldGoalsMade: 10.2,
        fieldGoalsAttempted: 19.5,
        freeThrowsMade: 6.2,
        freeThrowsAttempted: 8.1,
        offensiveRebounds: 2.2,
        defensiveRebounds: 7.8,
        personalFouls: 2.8,
        defensiveRating: 105.8
      }
    },
    lastMatchup: {
      date: '2024-02-01',
      winner: 2,
      player1Points: 28,
      player2Points: 31,
      gameId: 12346
    }
  },
  '4-5': {
    matchups: 28,
    player1Wins: 15,
    player2Wins: 13,
    averagePointDiff: 5.2,
    headToHeadStats: {
      player1: {
        points: 32.4,
        assists: 5.5,
        rebounds: 11.8,
        steals: 1.2,
        blocks: 1.5,
        turnovers: 3.1,
        fieldGoalPercentage: 54.2,
        threePointPercentage: 32.5,
        freeThrowPercentage: 75.8,
        gamesPlayed: 30,
        minutesPerGame: 36.2,
        plusMinus: 7.8,
        playerEfficiencyRating: 28.4,
        fieldGoalsMade: 12.2,
        fieldGoalsAttempted: 22.5,
        freeThrowsMade: 6.8,
        freeThrowsAttempted: 9.0,
        offensiveRebounds: 2.5,
        defensiveRebounds: 9.3,
        personalFouls: 2.8,
        defensiveRating: 104.2
      },
      player2: {
        points: 31.8,
        assists: 4.2,
        rebounds: 10.5,
        steals: 0.9,
        blocks: 2.1,
        turnovers: 3.0,
        fieldGoalPercentage: 52.4,
        threePointPercentage: 33.8,
        freeThrowPercentage: 84.5,
        gamesPlayed: 28,
        minutesPerGame: 33.8,
        plusMinus: 6.9,
        playerEfficiencyRating: 26.8,
        fieldGoalsMade: 11.5,
        fieldGoalsAttempted: 19.5,
        freeThrowsMade: 5.9,
        freeThrowsAttempted: 8.1,
        offensiveRebounds: 1.8,
        defensiveRebounds: 8.7,
        personalFouls: 2.5,
        defensiveRating: 106.8
      }
    },
    lastMatchup: {
      date: '2024-01-28',
      winner: 4,
      player1Points: 35,
      player2Points: 32,
      gameId: 12347
    }
  },
  '6-7': {
    matchups: 32,
    player1Wins: 14,
    player2Wins: 18,
    averagePointDiff: 4.8,
    headToHeadStats: {
      player1: {
        points: 31.8,
        assists: 8.8,
        rebounds: 8.2,
        steals: 1.3,
        blocks: 0.4,
        turnovers: 3.9,
        fieldGoalPercentage: 48.5,
        threePointPercentage: 36.4,
        freeThrowPercentage: 77.8,
        gamesPlayed: 32,
        minutesPerGame: 36.5,
        plusMinus: 5.8,
        playerEfficiencyRating: 25.6,
        fieldGoalsMade: 11.2,
        fieldGoalsAttempted: 23.1,
        freeThrowsMade: 6.2,
        freeThrowsAttempted: 8.0,
        offensiveRebounds: 1.4,
        defensiveRebounds: 6.8,
        personalFouls: 2.3,
        defensiveRating: 108.5
      },
      player2: {
        points: 26.2,
        assists: 10.4,
        rebounds: 12.8,
        steals: 1.1,
        blocks: 0.9,
        turnovers: 3.3,
        fieldGoalPercentage: 64.5,
        threePointPercentage: 36.2,
        freeThrowPercentage: 82.4,
        gamesPlayed: 32,
        minutesPerGame: 34.2,
        plusMinus: 8.9,
        playerEfficiencyRating: 27.8,
        fieldGoalsMade: 9.8,
        fieldGoalsAttempted: 15.2,
        freeThrowsMade: 4.5,
        freeThrowsAttempted: 5.5,
        offensiveRebounds: 3.2,
        defensiveRebounds: 9.6,
        personalFouls: 2.7,
        defensiveRating: 102.3
      }
    },
    lastMatchup: {
      date: '2024-02-15',
      winner: 7,
      player1Points: 35,
      player2Points: 28,
      gameId: 12348
    }
  },
  '8-9': {
    matchups: 24,
    player1Wins: 13,
    player2Wins: 11,
    averagePointDiff: 3.5,
    headToHeadStats: {
      player1: {
        points: 29.8,
        assists: 4.6,
        rebounds: 8.5,
        steals: 1.5,
        blocks: 1.2,
        turnovers: 2.8,
        fieldGoalPercentage: 51.2,
        threePointPercentage: 38.5,
        freeThrowPercentage: 88.2,
        gamesPlayed: 28,
        minutesPerGame: 35.4,
        plusMinus: 6.2,
        playerEfficiencyRating: 26.3,
        fieldGoalsMade: 10.8,
        fieldGoalsAttempted: 21.1,
        freeThrowsMade: 5.8,
        freeThrowsAttempted: 6.6,
        offensiveRebounds: 1.8,
        defensiveRebounds: 6.7,
        personalFouls: 2.4,
        defensiveRating: 105.8
      },
      player2: {
        points: 28.4,
        assists: 5.8,
        rebounds: 4.2,
        steals: 0.8,
        blocks: 0.3,
        turnovers: 2.5,
        fieldGoalPercentage: 49.2,
        threePointPercentage: 39.4,
        freeThrowPercentage: 88.5,
        gamesPlayed: 24,
        minutesPerGame: 35.4,
        plusMinus: 4.5,
        playerEfficiencyRating: 22.8,
        fieldGoalsMade: 9.5,
        fieldGoalsAttempted: 19.3,
        freeThrowsMade: 5.2,
        freeThrowsAttempted: 5.9,
        offensiveRebounds: 0.8,
        defensiveRebounds: 3.4,
        personalFouls: 2.1,
        defensiveRating: 107.2
      }
    },
    lastMatchup: {
      date: '2024-02-08',
      winner: 8,
      player1Points: 32,
      player2Points: 29,
      gameId: 12349
    }
  },
  '5-7': {
    matchups: 18,
    player1Wins: 8,
    player2Wins: 10,
    averagePointDiff: 4.2,
    headToHeadStats: {
      player1: {
        points: 32.8,
        assists: 4.5,
        rebounds: 10.8,
        steals: 0.9,
        blocks: 2.1,
        turnovers: 3.4,
        fieldGoalPercentage: 53.5,
        threePointPercentage: 33.8,
        freeThrowPercentage: 84.8,
        gamesPlayed: 18,
        minutesPerGame: 34.8,
        plusMinus: 6.8,
        playerEfficiencyRating: 27.5,
        fieldGoalsMade: 12.0,
        fieldGoalsAttempted: 22.4,
        freeThrowsMade: 6.5,
        freeThrowsAttempted: 7.7,
        offensiveRebounds: 2.8,
        defensiveRebounds: 8.0,
        personalFouls: 2.6,
        defensiveRating: 104.5
      },
      player2: {
        points: 26.5,
        assists: 9.2,
        rebounds: 13.1,
        steals: 1.3,
        blocks: 0.9,
        turnovers: 3.2,
        fieldGoalPercentage: 62.8,
        threePointPercentage: 36.5,
        freeThrowPercentage: 82.8,
        gamesPlayed: 18,
        minutesPerGame: 33.9,
        plusMinus: 8.4,
        playerEfficiencyRating: 28.2,
        fieldGoalsMade: 10.2,
        fieldGoalsAttempted: 16.2,
        freeThrowsMade: 4.8,
        freeThrowsAttempted: 5.8,
        offensiveRebounds: 3.5,
        defensiveRebounds: 9.6,
        personalFouls: 2.4,
        defensiveRating: 101.8
      }
    },
    lastMatchup: {
      date: '2024-01-27',
      winner: 7,
      player1Points: 31,
      player2Points: 25,
      gameId: 12350
    }
  },
  '3-4': {
    matchups: 24,
    player1Wins: 13,
    player2Wins: 11,
    averagePointDiff: 4.5,
    headToHeadStats: {
      player1: {
        points: 26.8,
        assists: 7.9,
        rebounds: 7.2,
        steals: 1.2,
        blocks: 0.8,
        turnovers: 3.1,
        fieldGoalPercentage: 52.4,
        threePointPercentage: 35.8,
        freeThrowPercentage: 82.5,
        gamesPlayed: 24,
        minutesPerGame: 34.8,
        plusMinus: 6.4,
        playerEfficiencyRating: 24.9,
        fieldGoalsMade: 9.8,
        fieldGoalsAttempted: 18.7,
        freeThrowsMade: 5.8,
        freeThrowsAttempted: 7.0,
        offensiveRebounds: 1.1,
        defensiveRebounds: 6.1,
        personalFouls: 2.3,
        defensiveRating: 107.2
      },
      player2: {
        points: 28.4,
        assists: 5.5,
        rebounds: 6.8,
        steals: 1.4,
        blocks: 0.3,
        turnovers: 2.9,
        fieldGoalPercentage: 47.8,
        threePointPercentage: 41.5,
        freeThrowPercentage: 90.8,
        gamesPlayed: 25,
        minutesPerGame: 35.1,
        plusMinus: 6.2,
        playerEfficiencyRating: 23.7,
        fieldGoalsMade: 10.2,
        fieldGoalsAttempted: 19.5,
        freeThrowsMade: 6.2,
        freeThrowsAttempted: 8.1,
        offensiveRebounds: 2.2,
        defensiveRebounds: 7.8,
        personalFouls: 2.8,
        defensiveRating: 105.8
      }
    },
    lastMatchup: {
      date: '2024-02-01',
      winner: 2,
      player1Points: 28,
      player2Points: 31,
      gameId: 12346
    }
  }
};

export const mockPlayerHistory: Record<number, PlayerHistory> = {
  1: {
    matchups: [
      {
        date: '2024-01-15',
        type: 'regular',
        player1Score: 35,
        player2Score: 28,
        result: 'W'
      },
      // Add more matchups...
    ],
    seasons: [
      {
        season: '2023-24',
        team: 'Los Angeles Lakers',
        points: 28.9,
        assists: 7.5,
        rebounds: 8.3,
        steals: 1.3,
        blocks: 0.9,
        turnovers: 3.2,
        fieldGoalPercentage: 53.5,
        threePointPercentage: 32.1,
        freeThrowPercentage: 75.9,
        gamesPlayed: 55,
        gamesStarted: 55,
        minutesPerGame: 35.5,
        plusMinus: 5.8,
        winPercentage: 0.545,
        playoffAppearance: true,
        playerEfficiencyRating: 24.8,
        fieldGoalsMade: 10.5,
        fieldGoalsAttempted: 19.6,
        freeThrowsMade: 5.2,
        freeThrowsAttempted: 6.8,
        offensiveRebounds: 1.2,
        defensiveRebounds: 7.1,
        personalFouls: 1.9,
        defensiveRating: 110.5
      },
      {
        season: '2022-23',
        team: 'Los Angeles Lakers',
        points: 28.9,
        assists: 6.8,
        rebounds: 8.3,
        steals: 0.9,
        blocks: 0.6,
        turnovers: 3.1,
        fieldGoalPercentage: 50.0,
        threePointPercentage: 32.1,
        freeThrowPercentage: 76.8,
        gamesPlayed: 55,
        gamesStarted: 54,
        minutesPerGame: 35.5,
        plusMinus: 3.8,
        winPercentage: 0.524,
        playoffAppearance: true,
        playerEfficiencyRating: 23.9,
        fieldGoalsMade: 10.2,
        fieldGoalsAttempted: 20.4,
        freeThrowsMade: 5.1,
        freeThrowsAttempted: 6.6,
        offensiveRebounds: 1.2,
        defensiveRebounds: 7.1,
        personalFouls: 1.6,
        defensiveRating: 112.3
      },
      // Add more seasons...
    ],
    careerHighs: {
      points: { value: 61, date: '2014-03-03', opponent: 'Charlotte Bobcats' },
      assists: { value: 19, date: '2018-03-21', opponent: 'Toronto Raptors' },
      rebounds: { value: 19, date: '2012-05-13', opponent: 'Indiana Pacers' },
      steals: { value: 8, date: '2012-02-12', opponent: 'Milwaukee Bucks' },
      blocks: { value: 5, date: '2016-04-06', opponent: 'Milwaukee Bucks' }
    },
    awards: [
      { season: '2023-24', award: 'All-Time Scoring Leader' },
      { season: '2019-20', award: 'NBA Champion' },
      { season: '2019-20', award: 'Finals MVP' },
      { season: '2019-20', award: 'All-NBA First Team' },
      // Add more awards...
    ]
  },
  7: {
    matchups: [
      {
        date: '2024-01-15',
        type: 'regular',
        player1Score: 35,
        player2Score: 28,
        result: 'W'
      },
      // Add more matchups...
    ],
    seasons: [
      {
        season: '2023-24',
        team: 'Denver Nuggets',
        points: 25.4,
        assists: 9.8,
        rebounds: 12.3,
        steals: 1.2,
        blocks: 0.8,
        turnovers: 3.5,
        fieldGoalPercentage: 63.2,
        threePointPercentage: 35.8,
        freeThrowPercentage: 81.2,
        gamesPlayed: 57,
        gamesStarted: 57,
        minutesPerGame: 33.6,
        plusMinus: 9.4,
        winPercentage: 0.652,
        playoffAppearance: true,
        playerEfficiencyRating: 31.5,
        fieldGoalsMade: 9.8,
        fieldGoalsAttempted: 15.5,
        freeThrowsMade: 4.2,
        freeThrowsAttempted: 5.2,
        offensiveRebounds: 2.8,
        defensiveRebounds: 9.5,
        personalFouls: 2.5,
        defensiveRating: 108.2
      },
      {
        season: '2022-23',
        team: 'Denver Nuggets',
        points: 24.5,
        assists: 9.8,
        rebounds: 11.8,
        steals: 1.3,
        blocks: 0.7,
        turnovers: 3.6,
        fieldGoalPercentage: 63.2,
        threePointPercentage: 38.0,
        freeThrowPercentage: 82.2,
        gamesPlayed: 69,
        gamesStarted: 69,
        minutesPerGame: 33.7,
        plusMinus: 8.9,
        winPercentage: 0.659,
        playoffAppearance: true,
        playerEfficiencyRating: 31.2,
        fieldGoalsMade: 9.4,
        fieldGoalsAttempted: 14.9,
        freeThrowsMade: 4.1,
        freeThrowsAttempted: 5.0,
        offensiveRebounds: 2.4,
        defensiveRebounds: 9.4,
        personalFouls: 2.5,
        defensiveRating: 109.5
      }
    ],
    careerHighs: {
      points: { value: 50, date: '2023-11-08', opponent: 'Indiana Pacers' },
      assists: { value: 18, date: '2022-03-06', opponent: 'New Orleans Pelicans' },
      rebounds: { value: 27, date: '2021-12-06', opponent: 'Chicago Bulls' },
      steals: { value: 7, date: '2021-02-12', opponent: 'Oklahoma City Thunder' },
      blocks: { value: 6, date: '2022-01-19', opponent: 'Los Angeles Clippers' }
    },
    awards: [
      { season: '2022-23', award: 'NBA Champion' },
      { season: '2022-23', award: 'Finals MVP' },
      { season: '2022-23', award: 'All-NBA First Team' },
      { season: '2020-21', award: 'NBA MVP' },
      // Add more awards...
    ]
  }
  // Add more player histories...
}; 