name: Verify Secrets

on: workflow_dispatch

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq
        
      - name: Check Firebase Configuration
        run: |
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then
            echo "❌ FIREBASE_API_KEY is not set"
            exit 1
          else
            echo "✅ FIREBASE_API_KEY is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_AUTH_DOMAIN }}" ]; then
            echo "❌ FIREBASE_AUTH_DOMAIN is not set"
            exit 1
          else
            echo "✅ FIREBASE_AUTH_DOMAIN is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]; then
            echo "❌ FIREBASE_PROJECT_ID is not set"
            exit 1
          else
            echo "✅ FIREBASE_PROJECT_ID is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_STORAGE_BUCKET }}" ]; then
            echo "❌ FIREBASE_STORAGE_BUCKET is not set"
            exit 1
          else
            echo "✅ FIREBASE_STORAGE_BUCKET is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" ]; then
            echo "❌ FIREBASE_MESSAGING_SENDER_ID is not set"
            exit 1
          else
            echo "✅ FIREBASE_MESSAGING_SENDER_ID is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_APP_ID }}" ]; then
            echo "❌ FIREBASE_APP_ID is not set"
            exit 1
          else
            echo "✅ FIREBASE_APP_ID is set"
          fi
          
          if [ -z "${{ secrets.FIREBASE_MEASUREMENT_ID }}" ]; then
            echo "❌ FIREBASE_MEASUREMENT_ID is not set"
            exit 1
          else
            echo "✅ FIREBASE_MEASUREMENT_ID is set"
          fi

      - name: Verify Service Account JSON Format
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "❌ FIREBASE_SERVICE_ACCOUNT is not set"
            exit 1
          else
            echo "✅ FIREBASE_SERVICE_ACCOUNT is set"
            # Verify JSON format (without exposing the content)
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | jq empty && echo "✅ Service account is valid JSON" || echo "❌ Invalid JSON format"
          fi 